name: CI
on:
  #  schedule:
  #  - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  copernicus-scraping:
    name: Scrap opendatalapalma.es looking for La Palma Volcano data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: python main.py -vn
        env:
          NOTIFICATION_FROM_ADDR: ${{ secrets.NOTIFICATION_FROM_ADDR }}
          NOTIFICATION_TO_ADDRS: ${{ secrets.NOTIFICATION_TO_ADDRS }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          KEYVALUE_API_URL: ${{ secrets.KEYVALUE_API_URL }}
